services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: mushee
      POSTGRES_PASSWORD: mushee
      POSTGRES_DB: mushee
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
