services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: mushee
      POSTGRES_PASSWORD: mushee
      POSTGRES_DB: mushee
    ports:
      - '5632:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
