# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_pb2 as inference__pb2


class CrepeInferenceStub(object):
    """Pitch-model forward passes, factored out of the API so they can run in
    separate, independently-scaled services. The API keeps all framing, caching,
    segmentation, note extraction and MusicXML building — these RPCs do ONLY the
    neural-net forward pass. Tensors are flat little-endian float32 bytes plus an
    explicit shape, so no language-specific tensor encoding leaks across the wire.

    ── CREPE ────────────────────────────────────────────────────────────────────
    Forward pass only: framing (normalizeFrame), the activation cache, Viterbi and
    segmentation stay in the API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/mushee.inference.v1.CrepeInference/Predict',
                request_serializer=inference__pb2.CrepePredictRequest.SerializeToString,
                response_deserializer=inference__pb2.CrepePredictResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/mushee.inference.v1.CrepeInference/Health',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                )


class CrepeInferenceServicer(object):
    """Pitch-model forward passes, factored out of the API so they can run in
    separate, independently-scaled services. The API keeps all framing, caching,
    segmentation, note extraction and MusicXML building — these RPCs do ONLY the
    neural-net forward pass. Tensors are flat little-endian float32 bytes plus an
    explicit shape, so no language-specific tensor encoding leaks across the wire.

    ── CREPE ────────────────────────────────────────────────────────────────────
    Forward pass only: framing (normalizeFrame), the activation cache, Viterbi and
    segmentation stay in the API.
    """

    def Predict(self, request, context):
        """Input: a batch of normalized analysis windows. Output: per-frame sigmoid
        activations. Confidence (row max) is derived API-side, so it isn't returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrepeInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=inference__pb2.CrepePredictRequest.FromString,
                    response_serializer=inference__pb2.CrepePredictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mushee.inference.v1.CrepeInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrepeInference(object):
    """Pitch-model forward passes, factored out of the API so they can run in
    separate, independently-scaled services. The API keeps all framing, caching,
    segmentation, note extraction and MusicXML building — these RPCs do ONLY the
    neural-net forward pass. Tensors are flat little-endian float32 bytes plus an
    explicit shape, so no language-specific tensor encoding leaks across the wire.

    ── CREPE ────────────────────────────────────────────────────────────────────
    Forward pass only: framing (normalizeFrame), the activation cache, Viterbi and
    segmentation stay in the API.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mushee.inference.v1.CrepeInference/Predict',
            inference__pb2.CrepePredictRequest.SerializeToString,
            inference__pb2.CrepePredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mushee.inference.v1.CrepeInference/Health',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BasicPitchInferenceStub(object):
    """── basic-pitch ────────────────────────────────────────────────────────────--
    Replicates evaluateModel (2 s-window framing, per-window predict, overlap-trim
    stitch) and returns the note + onset activation matrices. outputToNotesPoly
    and note→time mapping stay in the API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.unary_unary(
                '/mushee.inference.v1.BasicPitchInference/Forward',
                request_serializer=inference__pb2.BasicPitchForwardRequest.SerializeToString,
                response_deserializer=inference__pb2.BasicPitchForwardResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/mushee.inference.v1.BasicPitchInference/Health',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                )


class BasicPitchInferenceServicer(object):
    """── basic-pitch ────────────────────────────────────────────────────────────--
    Replicates evaluateModel (2 s-window framing, per-window predict, overlap-trim
    stitch) and returns the note + onset activation matrices. outputToNotesPoly
    and note→time mapping stay in the API.
    """

    def Forward(self, request, context):
        """Input: mono 22050 Hz PCM. Output: frames + onsets activation matrices [T,88].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicPitchInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=inference__pb2.BasicPitchForwardRequest.FromString,
                    response_serializer=inference__pb2.BasicPitchForwardResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mushee.inference.v1.BasicPitchInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BasicPitchInference(object):
    """── basic-pitch ────────────────────────────────────────────────────────────--
    Replicates evaluateModel (2 s-window framing, per-window predict, overlap-trim
    stitch) and returns the note + onset activation matrices. outputToNotesPoly
    and note→time mapping stay in the API.
    """

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mushee.inference.v1.BasicPitchInference/Forward',
            inference__pb2.BasicPitchForwardRequest.SerializeToString,
            inference__pb2.BasicPitchForwardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mushee.inference.v1.BasicPitchInference/Health',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
