# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x13mushee.inference.v1\"N\n\x13\x43repePredictRequest\x12\x0e\n\x06\x66rames\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62\x61tch_count\x18\x02 \x01(\x05\x12\x12\n\nframe_size\x18\x03 \x01(\x05\"R\n\x14\x43repePredictResponse\x12\x13\n\x0b\x61\x63tivations\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62\x61tch_count\x18\x02 \x01(\x05\x12\x10\n\x08num_bins\x18\x03 \x01(\x05\"+\n\x18\x42\x61sicPitchForwardRequest\x12\x0f\n\x07samples\x18\x01 \x01(\x0c\"d\n\x19\x42\x61sicPitchForwardResponse\x12\x0e\n\x06\x66rames\x18\x01 \x01(\x0c\x12\x0e\n\x06onsets\x18\x02 \x01(\x0c\x12\x12\n\nnum_frames\x18\x03 \x01(\x05\x12\x13\n\x0bnum_pitches\x18\x04 \x01(\x05\"\x0f\n\rHealthRequest\".\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05model\x18\x02 \x01(\t2\xc3\x01\n\x0e\x43repeInference\x12^\n\x07Predict\x12(.mushee.inference.v1.CrepePredictRequest\x1a).mushee.inference.v1.CrepePredictResponse\x12Q\n\x06Health\x12\".mushee.inference.v1.HealthRequest\x1a#.mushee.inference.v1.HealthResponse2\xd2\x01\n\x13\x42\x61sicPitchInference\x12h\n\x07\x46orward\x12-.mushee.inference.v1.BasicPitchForwardRequest\x1a..mushee.inference.v1.BasicPitchForwardResponse\x12Q\n\x06Health\x12\".mushee.inference.v1.HealthRequest\x1a#.mushee.inference.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREPEPREDICTREQUEST']._serialized_start=40
  _globals['_CREPEPREDICTREQUEST']._serialized_end=118
  _globals['_CREPEPREDICTRESPONSE']._serialized_start=120
  _globals['_CREPEPREDICTRESPONSE']._serialized_end=202
  _globals['_BASICPITCHFORWARDREQUEST']._serialized_start=204
  _globals['_BASICPITCHFORWARDREQUEST']._serialized_end=247
  _globals['_BASICPITCHFORWARDRESPONSE']._serialized_start=249
  _globals['_BASICPITCHFORWARDRESPONSE']._serialized_end=349
  _globals['_HEALTHREQUEST']._serialized_start=351
  _globals['_HEALTHREQUEST']._serialized_end=366
  _globals['_HEALTHRESPONSE']._serialized_start=368
  _globals['_HEALTHRESPONSE']._serialized_end=414
  _globals['_CREPEINFERENCE']._serialized_start=417
  _globals['_CREPEINFERENCE']._serialized_end=612
  _globals['_BASICPITCHINFERENCE']._serialized_start=615
  _globals['_BASICPITCHINFERENCE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
